name: 'Go multi-project action'
description: 'Run command on multiple go projects'
inputs:
  command:
    description: 'Command to execute'
    required: true
  repositories: 
    description: 'Projects to execute on'
    required: true
outputs:
  status:
    description: 'Status of execution'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.repositories }}